<?php
/**
 * This file is part of the Simple Web Demo Free Lottery Management Application.
 *
 * This project is no longer maintained.
 * The project is written in Laminas Framework Release.
 *
 * @link https://github.com/scorpion3dd
 * @author Denis Puzik <scorpion3dd@gmail.com>
 * @copyright Copyright (c) 2021-2022 scorpion3dd
 */

declare(strict_types=1);

use Application\Form\LogForm;
use Application\View\Helper\Breadcrumbs;
use Application\View\Helper\Menu;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */
$this->headTitle($this->translate('Add Log'));
/** @var Menu $menu */
$menu = $this->mainMenu();
$menu->setActiveItemId('logs');
/** @var Breadcrumbs $breadcrumbs */
$breadcrumbs = $this->pageBreadcrumbs();
$breadcrumbs->setItems([
    $this->translate('Home') => $this->url('home'),
    $this->translate('Logs') => $this->url('logs'),
    $this->translate('Add Log') => $this->url('logs', ['action' => 'add'])
]);
/** @var LogForm $form */
$form->get('message')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter message'
]);
$form->get('timestamp')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'YYYY-MM-DD'
]);
$form->get('priority')->setAttributes([
    'class' => 'form-control'
]);
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();
?>
<h1><?= $this->translate('Add Log'); ?></h1>
<p>
    <?= $this->translate('Please fill out the following form and click the Create button.'); ?>
</p>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('message')); ?>
            <?= $this->formElement($form->get('message')); ?>
            <?= $this->formElementErrors($form->get('message')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('timestamp')); ?>
            <?= $this->formElement($form->get('timestamp')); ?>
            <?= $this->formElementErrors($form->get('timestamp')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('priority')); ?>
            <?= $this->formElement($form->get('priority')); ?>
            <?= $this->formElementErrors($form->get('priority')); ?>
        </div>
        <?= $this->formElement($form->get('csrf')); ?>
        <?= $this->formElementErrors($form->get('csrf')); ?>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
