<?php
/**
 * This file is part of the Simple Web Demo Free Lottery Management Application.
 *
 * This project is no longer maintained.
 * The project is written in Laminas Framework Release.
 *
 * @link https://github.com/scorpion3dd
 * @author Denis Puzik <scorpion3dd@gmail.com>
 * @copyright Copyright (c) 2021-2022 scorpion3dd
 */

declare(strict_types=1);

use Application\Document\Log;
use Application\Form\LogForm;
use Application\View\Helper\Breadcrumbs;
use Application\View\Helper\Menu;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */
$this->headTitle($this->translate('Edit Log'));
/** @var Menu $menu */
$menu = $this->mainMenu();
$menu->setActiveItemId('logs');
/** @var Log $log */
/** @var Breadcrumbs $breadcrumbs */
$breadcrumbs = $this->pageBreadcrumbs();
$breadcrumbs->setItems([
    $this->translate('Home') => $this->url('home'),
    $this->translate('Logs') => $this->url('logs'),
    $this->translate('Edit Log') => $this->url('logs', ['action' => 'edit', 'id' => $log->getId()])
]);
/** @var LogForm $form */
$form->get('message')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter message'
]);
$form->get('priority')->setAttributes([
    'class' => 'form-control'
]);
$form->get('submit')
    ->setAttributes(['class' => 'btn btn-primary'])
    ->setValue('Save')
    ->setLabel($this->translate('Save'));
$form->prepare();
?>
<h1><?= $this->translate('Edit Log'); ?> <?= $this->escapeHtml($log->getId()) ?></h1>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('message')); ?>
            <?= $this->formElement($form->get('message')); ?>
            <?= $this->formElementErrors($form->get('message')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('priority')); ?>
            <?= $this->formElement($form->get('priority')); ?>
            <?= $this->formElementErrors($form->get('priority')); ?>
        </div>
        <?= $this->formElement($form->get('csrf')); ?>
        <?= $this->formElementErrors($form->get('csrf')); ?>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>