<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentLogHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate(object $document, array $data, array $hints = array()): array
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['extra']) || (! empty($this->class->fieldMappings['extra']['nullable']) && array_key_exists('extra', $data))) {
            $value = $data['extra'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['extra']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['extra']->setValue($document, $return);
            $hydratedData['extra'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['message']) || (! empty($this->class->fieldMappings['message']['nullable']) && array_key_exists('message', $data))) {
            $value = $data['message'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['message']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['message']->setValue($document, $return);
            $hydratedData['message'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['priority']) || (! empty($this->class->fieldMappings['priority']['nullable']) && array_key_exists('priority', $data))) {
            $value = $data['priority'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['priority']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['priority']->setValue($document, $return);
            $hydratedData['priority'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['priorityName']) || (! empty($this->class->fieldMappings['priorityName']['nullable']) && array_key_exists('priorityName', $data))) {
            $value = $data['priorityName'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['priorityName']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['priorityName']->setValue($document, $return);
            $hydratedData['priorityName'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['timestamp'])) {
            $value = $data['timestamp'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['timestamp']->setValue($document, clone $return);
            $hydratedData['timestamp'] = $return;
        }
        return $hydratedData;
    }
}