# This is a build configuration for PHP.
#
# This file is part of the Simple Web Demo Free Lottery Management Application.
#
# This project is no longer maintained.
# The project is written in Laminas Framework Release.
#
# @link https://github.com/scorpion3dd
# @author Denis Puzik <scorpion3dd@gmail.com>
# @copyright Copyright (c) 2021-2022 scorpion3dd

image: php:8.0

pipelines:
  default:
    - step:
        name: Init build
        caches:
          - composer
        script:
          - php -v
          - pear -V
          - pecl -V
          - apt-get update && apt-get install -y unzip git zlib1g-dev libicu-dev g++ libzip-dev libxml2-dev libfreetype6-dev libxft-dev pkg-config libjpeg62-turbo-dev redis gnupg
          - pecl install mongodb
          - docker-php-ext-enable mongodb
          - pecl install redis
          - docker-php-ext-enable redis
#          - docker-php-ext-configure -j$(nproc) gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
          - docker-php-ext-install -j$(nproc) gd
          - docker-php-ext-install -j$(nproc) intl
          - docker-php-ext-install -j$(nproc) xml
          - docker-php-ext-install -j$(nproc) zip
          - docker-php-ext-install -j$(nproc) calendar
          - docker-php-ext-install -j$(nproc) dom
          - docker-php-ext-install -j$(nproc) pdo
          - docker-php-ext-install -j$(nproc) pdo_mysql
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.1.5
          - composer --version
          - composer install --ignore-platform-reqs
          - composer cs-check
          - composer stan-check
          - chmod -R 777 data/cache
          - chmod -R 777 data/cache_test
          - chmod -R 777 data/logs
          - chmod -R 777 public/img/captcha
          - cp config/autoload/local.php.dist config/autoload/local.php
          - cp config/autoload/module.doctrine-mongo-odm.local.php.dist config/autoload/module.doctrine-mongo-odm.local.php
          - cp config/autoload_test/local.php.dist config/autoload_test/local.php
          - cp config/autoload_test/module.doctrine-mongo-odm.local.php.dist config/autoload_test/module.doctrine-mongo-odm.local.php
          - composer test-unit
          - redis-cli -h localhost ping
        services:
          - redis
          - mysql
          - mongo
definitions:
  services:
    redis:
      image: redis:5.0
    mysql:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: 'laminas_mvc_demo'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'laminas_mvc_demo'
        MYSQL_PASSWORD: 'laminas_mvc_demo123'
    mongo:
      image: mongo:5.0