# This is a build configuration for PHP.
#
# This file is part of the Simple Web Demo Free Lottery Management Application.
#
# This project is no longer maintained.
# The project is written in Laminas Framework Release.
#
# @link https://github.com/scorpion3dd
# @author Denis Puzik <scorpion3dd@gmail.com>
# @copyright Copyright (c) 2021-2022 scorpion3dd

services:
  laminas:
    build: .
    ports:
     - "8080:80"
    volumes:
     - .:/var/www
