<?php
/**
 * This file is part of the Simple Web Demo Free Lottery Management Application.
 *
 * This project is no longer maintained.
 * The project is written in Laminas Framework Release.
 *
 * @link https://github.com/scorpion3dd
 * @author Denis Puzik <scorpion3dd@gmail.com>
 * @copyright Copyright (c) 2021-2022 scorpion3dd
 */

declare(strict_types=1);

use Application\View\Helper\Menu;
use User\Form\LoginForm;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */
$this->headTitle($this->translate('Sign in'));
/** @var Menu $menu */
$menu = $this->mainMenu();
$menu->setActiveItemId('login');
/** @var LoginForm $form */
$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Email address',
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
$form->get('password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Password',
    'required' => true,
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
/** @var bool $isLoginError */
?>
<div class="row">
    <div class="col-md-offset-4 col-md-3">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading"><?= $this->translate('Please sign in'); ?></h2>
            <?php if ($isLoginError) : ?>
            <div class="alert alert-warning" role="alert">
                <?= $this->translate('Incorrect login and/or password.'); ?>
                <a href="<?= $this->url('reset-password') ?>"><?= $this->translate('Forgot password'); ?>?</a>
            </div>
            <?php endif; ?>
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <div class="checkbox">
                <label>
                    <?= $this->formElement($form->get('remember_me')); ?> <?= $this->translate('Remember me'); ?>
                </label>
            </div>
            <?= $this->formElement($form->get('redirect_url')); ?>
            <?= $this->formElement($form->get('csrf')) ?>
            <button class="btn btn-lg btn-primary btn-block" type="submit"><?= $this->translate('Sign in'); ?></button>
        </form>
    </div>
</div>