<?php
/**
 * This file is part of the Simple Web Demo Free Lottery Management Application.
 *
 * This project is no longer maintained.
 * The project is written in Laminas Framework Release.
 *
 * @link https://github.com/scorpion3dd
 * @author Denis Puzik <scorpion3dd@gmail.com>
 * @copyright Copyright (c) 2021-2022 scorpion3dd
 */

declare(strict_types=1);

use Application\View\Helper\Breadcrumbs;
use Application\View\Helper\Menu;
use User\Form\UserForm;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */
$this->headTitle($this->translate('Add User'));
/** @var Menu $menu */
$menu = $this->mainMenu();
$menu->setActiveItemId('users');
/** @var Breadcrumbs $breadcrumbs */
$breadcrumbs = $this->pageBreadcrumbs();
$breadcrumbs->setItems([
    $this->translate('Home') => $this->url('home'),
    $this->translate('Manage Users') => $this->url('users'),
    $this->translate('Add User') => $this->url('users', ['action' => 'add'])
]);
/** @var UserForm $form */
$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'name@example.com'
    ]);
$form->get('full_name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => $this->translate('John Doe')
    ]);
$form->get('description')->setAttributes([
    'class' => 'form-control',
    'placeholder' => $this->translate('Description')
    ]);
$form->get('date_birthday')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'YYYY-MM-DD'
]);
$form->get('status')->setAttributes([
    'class' => 'form-control'
    ]);
$form->get('access')->setAttributes([
    'class' => 'form-control'
]);
$form->get('gender')->setAttributes([
    'class' => 'form-control'
]);
$form->get('password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter password',
    ]);
$form->get('confirm_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Retype password',
    ]);
$form->get('roles')->setAttributes([
    'class' => 'form-control'
    ]);
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();
?>
<h1><?= $this->translate('Add User'); ?></h1>
<p>
    <?= $this->translate('Please fill out the following form and click the Create button.'); ?>
</p>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('date_birthday')); ?>
            <?= $this->formElement($form->get('date_birthday')); ?>
            <?= $this->formElementErrors($form->get('date_birthday')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_password')); ?>
            <?= $this->formElement($form->get('confirm_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_password')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('gender')); ?>
            <?= $this->formElement($form->get('gender')); ?>
            <?= $this->formElementErrors($form->get('gender')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('access')); ?>
            <?= $this->formElement($form->get('access')); ?>
            <?= $this->formElementErrors($form->get('access')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('roles')); ?>
            <?= $this->formElement($form->get('roles')); ?>
            <?= $this->formElementErrors($form->get('roles')); ?>                  
        </div>
        <?= $this->formElement($form->get('csrf')); ?>
        <?= $this->formElementErrors($form->get('csrf')); ?>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>