<?php
/**
 * This file is part of the Simple Web Demo Free Lottery Management Application.
 *
 * This project is no longer maintained.
 * The project is written in Laminas Framework Release.
 *
 * @link https://github.com/scorpion3dd
 * @author Denis Puzik <scorpion3dd@gmail.com>
 * @copyright Copyright (c) 2021-2022 scorpion3dd
 */

declare(strict_types=1);

use Application\View\Helper\Breadcrumbs;
use Application\View\Helper\Menu;
use User\Entity\User;
use User\Form\PasswordChangeForm;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */
$this->headTitle($this->translate('Change Password'));
/** @var Menu $menu */
$menu = $this->mainMenu();
$menu->setActiveItemId('users');
/** @var User $user */
/** @var Breadcrumbs $breadcrumbs */
$breadcrumbs = $this->pageBreadcrumbs();
$breadcrumbs->setItems([
    $this->translate('Home') => $this->url('home'),
    $this->translate('Manage Users') => $this->url('users'),
    $this->translate('Change Password') => $this->url('users', ['action' => 'change-password', 'id' => $user->getId()])
]);
/** @var PasswordChangeForm $form */
$form->get('old_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter old password'
    ]);
$form->get('new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter new password'
    ]);
$form->get('confirm_new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Re-enter new password'
    ]);
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();
?>
<h1><?= $this->translate('Change Password for'); ?> <?= $this->escapeHtml($user->getEmail()) ?></h1>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('old_password')); ?>
            <?= $this->formElement($form->get('old_password')); ?>
            <?= $this->formElementErrors($form->get('old_password')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('new_password')); ?>
            <?= $this->formElement($form->get('new_password')); ?>
            <?= $this->formElementErrors($form->get('new_password')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <?= $this->formElement($form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>                  
        </div>
        <?= $this->formElement($form->get('csrf')); ?>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>