<?php
/**
 * This file is part of the Simple Web Demo Free Lottery Management Application.
 *
 * This project is no longer maintained.
 * The project is written in Laminas Framework Release.
 *
 * @link https://github.com/scorpion3dd
 * @author Denis Puzik <scorpion3dd@gmail.com>
 * @copyright Copyright (c) 2021-2022 scorpion3dd
 */

declare(strict_types=1);

use User\Form\PasswordResetForm;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */
$this->headTitle($this->translate('Reset Password'));
/** @var PasswordResetForm $form */
$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Email address'
    ]);
$form->get('submit')->setAttributes([
    'class' => 'btn btn-large btn-primary'
    ]);
$form->prepare();
?>
<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>
        <h2><?= $this->translate('Reset Password'); ?></h2>
        <p><?= $this->translate('Enter your e-mail address below to reset your password'); ?></p>
        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>
        <?php if ($form->has('captcha')) : ?>
            <?= $this->formElement($form->get('captcha')); ?>
            <p class="hint"><?= $this->translate('Enter the letters above as you see them.'); ?></p>
        <?php endif; ?>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->formElement($form->get('csrf')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>