<?php
/**
 * This file is part of the Simple Web Demo Free Lottery Management Application.
 *
 * This project is no longer maintained.
 * The project is written in Laminas Framework Release.
 *
 * @link https://github.com/scorpion3dd
 * @author Denis Puzik <scorpion3dd@gmail.com>
 * @copyright Copyright (c) 2021-2022 scorpion3dd
 */

declare(strict_types=1);

use User\Form\PasswordChangeForm;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */
$this->headTitle($this->translate('Set New Password'));
/** @var PasswordChangeForm $form */
$form->get('new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Type New Password'
    ]);
$form->get('confirm_new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Confirm New Password'
    ]);
$form->get('submit')->setAttributes([
    'class' => 'btn btn-primary'
    ]);
$form->prepare();
?>
<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>
        <h2><?= $this->translate('Set New Password'); ?></h2>
        <p><?= $this->translate('Enter your new password in the form below'); ?></p>
        <div class="form-group">
            <?= $this->formLabel($form->get('new_password')); ?>
            <?= $this->formElement($form->get('new_password')); ?>
            <?= $this->formElementErrors($form->get('new_password')); ?>                              
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <?= $this->formElement($form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>   
        </div>    
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->formElement($form->get('csrf')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>