<?php
/**
 * This file is part of the Simple Web Demo Free Lottery Management Application.
 *
 * This project is no longer maintained.
 * The project is written in Laminas Framework Release.
 *
 * @link https://github.com/scorpion3dd
 * @author Denis Puzik <scorpion3dd@gmail.com>
 * @copyright Copyright (c) 2021-2022 scorpion3dd
 */

declare(strict_types=1);

use Application\View\Helper\Breadcrumbs;
use Application\View\Helper\Menu;
use User\Entity\Role;
use User\Form\RolePermissionsForm;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */
/** @var Role $role */
$this->headTitle($this->translate('Edit Role Permissions'));
/** @var Menu $menu */
$menu = $this->mainMenu();
$menu->setActiveItemId('roles');
/** @var Breadcrumbs $breadcrumbs */
$breadcrumbs = $this->pageBreadcrumbs();
$breadcrumbs->setItems([
    $this->translate('Home') => $this->url('home'),
    $this->translate('Manage Roles') => $this->url('roles'),
    $this->translate('Edit Role') => $this->url('roles', ['action' => 'edit', 'id' => $role->getId()])
]);
/** @var RolePermissionsForm $form */
$form->get('submit')
        ->setAttributes(['class' => 'btn btn-primary'])
        ->setValue('Save');
$form->prepare();
/** @var array $allPermissions */
?>
<h1><?= $this->translate('Edit Permissions of'); ?> <?= $this->escapeHtml($role->getName()) ?></h1>
<div class="row">
    <div class="col-md-8">
        <?= $this->form()->openTag($form); ?>
        <table class="table table-striped table-bordered">
            <tr>
                <th><?= $this->translate('Name'); ?></th>
                <th><?= $this->translate('Description'); ?></th>
            </tr>
            <?php
            foreach ($allPermissions as $permission) :
                $element = $form->get('permissions')->get($permission->getName());
                ?>
            <tr>
                <td>
                    <div class="checkbox">
                        <label><input type="checkbox" name="<?= $this->escapeHtmlAttr($element->getName()) ?>" 
                                      value="<?= $this->escapeHtmlAttr($element->getCheckedValue()) ?>"
                                <?php
                                if ($element->isChecked()) {
                                    echo 'checked';
                                }
                                if ($element->getAttribute('disabled')) {
                                    echo 'disabled';
                                }
                                ?>
                            >
                            <?= $this->escapeHtml($element->getLabel()) ?>
                        </label>
                        <?= $this->formElementErrors($element); ?>                  
                    </div>
                </td>
                <td>
                    <?= $this->escapeHtml($permission->getDescription()) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?= $this->formElement($form->get('csrf')); ?>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-6">

    </div>    
</div>