<?php
/**
 * This file is part of the Simple Web Demo Free Lottery Management Application.
 *
 * This project is no longer maintained.
 * The project is written in Laminas Framework Release.
 *
 * @link https://github.com/scorpion3dd
 * @author Denis Puzik <scorpion3dd@gmail.com>
 * @copyright Copyright (c) 2021-2022 scorpion3dd
 */

declare(strict_types=1);

use Application\View\Helper\Breadcrumbs;
use Application\View\Helper\Menu;
use User\Entity\Permission;
use User\Entity\Role;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */
$this->headTitle($this->translate('View Role'));
/** @var Menu $menu */
$menu = $this->mainMenu();
$menu->setActiveItemId('roles');
/** @var array $allPermissions */
/** @var Role $role */
/** @var Breadcrumbs $breadcrumbs */
$breadcrumbs = $this->pageBreadcrumbs();
$breadcrumbs->setItems([
    $this->translate('Home') => $this->url('home'),
    $this->translate('Manage Roles') => $this->url('roles'),
    $this->translate('View Role') . $role->getName() => $this->url('roles', ['action' => 'view', 'id' => $role->getId()])
]);
?>
<h1><?= $this->translate('View Role'); ?> <?= $this->escapeHtml($role->getName()) ?></h1>
<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
<p>
<a class="btn btn-default" href="<?= $this->url('roles', ['action' => 'edit', 'id' => $role->getId()]); ?>">
    <span class="glyphicon glyphicon-pencil" ></span> <?= $this->translate('Edit Role'); ?>
</a>
</p>
<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($role->getId()) ?></td>
            </tr>
            <tr>
                <th><?= $this->translate('Name'); ?>:</th>
                <td><?= $this->escapeHtml($role->getName()) ?></td>
            </tr>
            <tr>
                <th><?= $this->translate('Description'); ?>:</th>
                <td><?= $this->escapeHtml($role->getDescription()) ?></td>
            </tr>
            <tr>
                <th><?= $this->translate('Date Created'); ?>:</th>
                <td><?= $this->escapeHtml($role->getDateCreated()->format('Y-m-d H:i:s')) ?></td>
            </tr>
        </table>
    </div>
</div>
<h2><?= $this->translate('Permissions'); ?></h2>
<p>
<a class="btn btn-default" href="<?= $this->url('roles', ['action' => 'editPermissions', 'id' => $role->getId()]) ?>">
  <span class="glyphicon glyphicon-check"></span> <?= $this->translate('Edit Permissions'); ?>
</a>
</p>
<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered">
            <tr>
                <th><?= $this->translate('Name'); ?></th>
                <th><?= $this->translate('Description'); ?></th>
            </tr>
            <?php /** @var Permission $permission */ ?>
            <?php foreach ($allPermissions as $permission) : ?>
            <tr>
                <td>
                    <input type="checkbox" disabled
                        <?php
                        if (isset($effectivePermissions[$permission->getName()])) {
                            echo 'checked';
                        }
                        ?>
                    >
                    <?= $this->escapeHtml($permission->getName()) ?>
                    <?php if (isset($effectivePermissions[$permission->getName()])
                        && $effectivePermissions[$permission->getName()] == 'inherited') : ?>
                    <em>(inherited)</em>
                    <?php endif; ?>
                </td>
                <td><?= $this->escapeHtml($permission->getDescription()) ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>