<?php
/**
 * This file is part of the Simple Web Demo Free Lottery Management Application.
 *
 * This project is no longer maintained.
 * The project is written in Laminas Framework Release.
 *
 * @link https://github.com/scorpion3dd
 * @author Denis Puzik <scorpion3dd@gmail.com>
 * @copyright Copyright (c) 2021-2022 scorpion3dd
 */

declare(strict_types=1);

use Application\View\Helper\Breadcrumbs;
use Application\View\Helper\Menu;
use User\Entity\Permission;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */
/** @var Permission $permission */
$this->headTitle($this->translate('View Permission'));
/** @var Menu $menu */
$menu = $this->mainMenu();
$menu->setActiveItemId('permissions');
/** @var Breadcrumbs $breadcrumbs */
$breadcrumbs = $this->pageBreadcrumbs();
$breadcrumbs->setItems([
    $this->translate('Home') => $this->url('home'),
    $this->translate('Manage Permissions') => $this->url('permissions'),
    $this->translate('View Permission') => $this->url('permissions', ['action' => 'view', 'id' => $permission->getId()])
]);
?>
<h1><?= $this->translate('View Permission'); ?></h1>
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($permission->getId()) ?></td>
            </tr>
            <tr>
                <th><?= $this->translate('Name'); ?>:</th>
                <td><?= $this->escapeHtml($permission->getName()) ?></td>
            </tr>
            <tr>
                <th><?= $this->translate('Description'); ?>:</th>
                <td><?= $this->escapeHtml($permission->getDescription()) ?></td>
            </tr>
            <tr>
                <th><?= $this->translate('Date Created'); ?>:</th>
                <td><?= $this->escapeHtml($permission->getDateCreated()->format('Y-m-d H:i:s')) ?></td>
            </tr>
        </table>
    </div>
</div>