<?php
/**
 * This file is part of the Simple Web Demo Free Lottery Management Application.
 *
 * This project is no longer maintained.
 * The project is written in Laminas Framework Release.
 *
 * @link https://github.com/scorpion3dd
 * @author Denis Puzik <scorpion3dd@gmail.com>
 * @copyright Copyright (c) 2021-2022 scorpion3dd
 */

declare(strict_types=1);

use Application\View\Helper\Breadcrumbs;
use Application\View\Helper\Menu;
use User\Entity\User;
use Laminas\Paginator\Paginator;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */
$this->headTitle($this->translate('Welcome'));
/** @var Menu $menu */
$menu = $this->mainMenu();
$menu->setActiveItemId('home');
/** @var Breadcrumbs $breadcrumbs */
$breadcrumbs = $this->pageBreadcrumbs();
$breadcrumbs->setItems([
     $this->translate('Home') => $this->url('home')
]);
?>
<h1><?= $this->translate('Welcome'); ?></h1>
<p>
    <?= $this->translate('This is the Simple Web Demo Free Lottery Management Application.'); ?>
    <br>
    <?= $this->translate('The "Free Lottery" application, freely available, allows to view a list of active users with open access to a very valuable resource at a given time.'); ?>
</p>
<table class="table table-striped">
    <tr>
        <th><?= $this->translate('E-mail'); ?></th>
        <th><?= $this->translate('Full Name'); ?></th>
        <th><?= $this->translate('Date Birthday'); ?></th>
        <th><?= $this->translate('Gender'); ?></th>
    </tr>
    <?php /** @var Paginator|null $users */ ?>
    <?php if (! empty($users)) : ?>
        <?php /** @var User $user */ ?>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td>
                    <a href="<?= $this->url('application', ['action' => 'view', 'id' => $user->getId()]); ?>">
                        <?= $this->escapeHtml($user->getEmail()); ?>
                    </a>
                </td>
                <td>
                    <?= $this->escapeHtml($user->getFullName()); ?>
                </td>
                <td><nobr><?= $this->escapeHtml($user->getDateBirthday()->format('Y-m-d')); ?></nobr></td>
                <td><?= $this->escapeHtml($this->translate($user->getGenderAsString())); ?></td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
</table>
<?php if (! empty($users)) : ?>
    <?= $this->paginationControl(
        $users,
        'Sliding',
        'application/partial/paginator',
        ['route' => 'home']
    );
    ?>
<?php endif; ?>
