<?php
/**
 * This file is part of the Simple Web Demo Free Lottery Management Application.
 *
 * This project is no longer maintained.
 * The project is written in Laminas Framework Release.
 *
 * @link https://github.com/scorpion3dd
 * @author Denis Puzik <scorpion3dd@gmail.com>
 * @copyright Copyright (c) 2021-2022 scorpion3dd
 */

declare(strict_types=1);

use Application\View\Helper\Breadcrumbs;
use Application\View\Helper\Menu;
use User\Entity\User;

use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */
$this->headTitle($this->translate('Settings'));
/** @var Menu $menu */
$menu = $this->mainMenu();
$menu->setActiveItemId('settings');
/** @var Breadcrumbs $breadcrumbs */
$breadcrumbs = $this->pageBreadcrumbs();
$breadcrumbs->setItems([
    $this->translate('Home') => $this->url('home'),
    $this->translate('Settings') => $this->url('application', ['action' => 'settings']),
]);
/** @var User $user */
?>
<h2><?= $this->translate('Settings'); ?></h2>
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></td>
            </tr>
            <tr>
                <th><?= $this->translate('E-mail'); ?>:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></td>
            </tr>
            <tr>
                <th><?= $this->translate('Full Name'); ?>:</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></td>
            </tr>
            <tr>
                <th><?= $this->translate('Date Birthday'); ?>:</th>
                <td><?= $this->escapeHtml($user->getDateBirthday()->format('Y-m-d')) ?></td>
            </tr>
            <tr>
                <th><?= $this->translate('Gender'); ?>:</th>
                <td><?= $this->escapeHtml($this->translate($user->getGenderAsString())) ?></td>
            </tr>
            <tr>
                <th><?= $this->translate('Access'); ?>:</th>
                <td><?= $this->escapeHtml($this->translate($user->getAccessAsString())) ?></td>
            </tr>
            <tr>
                <th><?= $this->translate('Date Time Created'); ?>:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()->format('Y-m-d H:i:s')) ?></td>
            </tr>
            <tr>
                <th><?= $this->translate('Date Time Updated'); ?>:</th>
                <td><?= $this->escapeHtml($user->getDateUpdated()->format('Y-m-d H:i:s')) ?></td>
            </tr>
        </table>
    </div>
</div>
